class ActionTypeUserToken:
    PASSWORD_RECOVERY = 1
    USER_PROFILE_CHANGE = 4

    CHOICES = (
        (PASSWORD_RECOVERY, 'PASSWORD_RECOVERY'),
        (USER_PROFILE_CHANGE, 'USER_PROFILE_CHANGE')
    )